name: blog_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: "3.0.2"


dependencies:
  flutter:
    sdk: flutter

  
  # service 
  dio: ^4.0.6

  # state
  flutter_riverpod: ^2.0.0-dev.9 

  #log
  logger: ^1.1.0
  
  # stroage
  shared_preferences: ^2.0.15

  # env
  flutter_dotenv: ^5.0.2
   
  # ui
  flutter_slidable: ^2.0.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - .env

